# #####################################################################
# Automatically generated by qmake (2.01a) Mon Nov 2 04:04:11 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
CONFIG += release 
INCLUDEPATH += "C:/Documents and Settings/vineeth/Desktop/loadregmain/." \
    .

# Input
HEADERS += registering.h \
    ui_registering.h
FORMS += registering.ui
SOURCES += main.cpp \
    registering.cpp
